### ISSUE TITLE
Exception when attempting to pull data 

### ISSUE THREAD

**Issue by bfurner** [sociome/sociome-data-commons#1]
I attempted to pull the data using the python code that is generated by the Sociome site

`import pandas as pd`
`df = pd.read_json('http://205.208.121.145/json/bad9a3f3-5bee-4e63-a6ab-28542aa90618')`

I get the following exception

`Exception has occurred: URLError`
`<urlopen error [Errno 60] Operation timed out>`
`TimeoutError: [Errno 60] Operation timed out`
`During handling of the above exception, another exception occurred:`
`  File "/Users/bfurner/Projects/test_sociome/sociome.py", line 2, in <module>`
`    df = pd.read_json('http://205.208.121.145/json/bad9a3f3-5bee-4e63-a6ab-28542aa90618')`
`urllib.error.URLError: <urlopen error [Errno 60] Operation timed out>`

**Comment by sjyk** [comment]
Fixed in release
