### ISSUE TITLE
Data dictionary limitations

### ISSUE THREAD

**Issue by sandra-tilmon** [sociome/sociome-data-commons#2]
To "Data category", consider adding:

> "Community data" for things like parks and the built environment, education, social cohesion, neighborhood physical disorder, community resilience, cultural beliefs and values, GINI index, isolation indices, homelessness, neighborhood social cohesion or disorder, neighborhood assets (NowPow)

> "Health data" for behavioral factors/psychological health and well-being, birth rates, death rates, health literacy, health insurance, 

To "Geographic unit": Add "Street address"

To data dictionary, consider adding: 

> "Link to website source" after "Collecting organization"

> "Data last updated as of" before/after "When accessed"

> "File type": "delimited text", "geojson", "geotiff", "other gis type", "MS Excel", "shapefile as zip", "XML",  "zip", "other"

**Comment by sandra-tilmon** [comment]
Oh, and "other" options for anything that doesn't conform to set choices to avoid miscategorizations with no indication for cleaning.

**Comment by bfurner** [comment]
I would also suggest including a field to capture licensing tied to the data set (e.g. CC BY-NC)

**Comment by sandra-tilmon** [comment]
Added fields except for file type (assuming we can grab that sytematically). - st
